Repository redacademy/orcbc-winter-2020, pull requests merged in 2020-03, with the labels that each got.

#4 update readme - add authors
  README.md
Labels: documentation

#7 Yx feature directory setup
  client/App.js
  client/index.js
  client/ios/Podfile.lock
  client/ios/orcbc.xcodeproj/project.pbxproj
  client/js/App.js
  client/package.json
  client/yarn.lock
Labels: good first issue

#17 Sl feature auth server
  server/generated/prisma-client/index.d.ts
  server/generated/prisma-client/index.js
  server/index.js
  server/resolvers.js
Labels: Epic, enhancement

#22 Sl feature auth flow
  client/ios/Podfile.lock
  client/js/App.js
  client/js/context/AuthProvider/AuthProvider.js
  client/js/context/AuthProvider/index.js
  client/js/navigation/index.js
  client/js/screens/Login/Login.js
  client/js/screens/Login/index.js
  client/js/screens/Signup/Signup.js
  client/js/screens/Signup/index.js
Labels: enhancement

#23 Rw feature map
  client/js/screens/CampMap/CampMap.js
  client/js/screens/CampMap/MapStyle.js
  client/js/screens/CampMap/styles.js
Labels: enhancement

#31 Sl feature auth flow
  client/js/App.js
  client/js/apollo/index.js
  client/js/context/AuthProvider/AuthProvider.js
  client/js/screens/Login/Login.js
  client/js/screens/Signup/Signup.js
  client/package.json
  client/yarn.lock
  server/package.json
Labels: enhancement

#32 Sid feature auth
  client/ios/Podfile.lock
  client/js/App.js
  client/js/apollo/index.js
  client/js/context/AuthProvider/AuthProvider.js
  client/js/screens/Login/Login.js
  client/js/screens/Login/styles.js
  client/js/screens/Profile/Profile.js
  client/js/screens/Signup/Signup.js
  client/js/screens/Signup/styles.js
  server/resolvers.js
  server/typeDefs.js
Labels: enhancement

#33 Sl feature auth flow
  client/ios/Podfile.lock
  client/js/screens/Login/Login.js
  client/js/screens/Signup/Signup.js
Labels: bug

#38 Sl feature auth flow
  client/js/context/AuthProvider/AuthProvider.js
  client/js/screens/Login/Login.js
Labels: enhancement
